### ISSUE TITLE
[Technical] Integrate MySQL database to API

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/rvm-api#21]
**[Technical task]** We need to setup the configuration and additional dependencies for connecting to the MySQL database server.

**Comment by claudiunicolaa** [comment]
Laravel has the capability of connecting to a MySQL database. All you need is to set the variables from `.env` based on MySQL database server configuration
```
DB_HOST=
DB_PORT=
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
```

Is it about this kind of configuration?

**Comment by RaduCStefanescu** [comment]
Hi @claudiunicolaa this issue was part of the desired scaffolding part of the project. As we went with using Docker, this was handled in #29 Will close this issue.

**Comment by RaduCStefanescu** [comment]
Closing this issue as it was handled in #29
